version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-massagebot}
      POSTGRES_USER: ${POSTGRES_USER:-massagebot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-massagebot}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    depends_on:
      - api
    restart: unless-stopped

volumes:
  db_data:
