"""admin+moderation+subscription

Revision ID: 7cf570c6f364
Revises: 400c93756461
Create Date: 2025-09-26 16:13:49.227490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cf570c6f364'
down_revision: Union[str, None] = '400c93756461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_ru', sa.String(length=128), nullable=False),
    sa.Column('name_lv', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('price_from', sa.Integer(), nullable=True),
    sa.Column('services', sa.JSON(), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('photos', sa.JSON(), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'frozen', name='profile_status'), server_default='pending', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('subscription_status', sa.Enum('none', 'active', 'past_due', 'suspended', 'cancelled', name='subscription_status'), server_default='none', nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('subscription_id', sa.String(length=64), nullable=True),
    sa.Column('next_billing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_public', sa.String(length=32), nullable=True),
    sa.Column('share_phone_publicly', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_city_id'), 'profiles', ['city_id'], unique=False)
    op.create_index(op.f('ix_profiles_is_published'), 'profiles', ['is_published'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_user_id', 'profile_id', name='uq_fav_client_profile')
    )
    op.create_index(op.f('ix_favorites_client_user_id'), 'favorites', ['client_user_id'], unique=False)
    op.add_column('users', sa.Column('tg_id', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('locale', sa.String(length=5), server_default='ru', nullable=True))
    op.add_column('users', sa.Column('share_phone_publicly', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'masseuse', 'client', name='role'),
               server_default='client',
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.drop_column('users', 'name_display')
    op.drop_column('users', 'email')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name_display', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=16),
               server_default=None,
               type_=postgresql.ENUM('admin', 'masseuse', 'client', name='role'),
               existing_nullable=False)
    op.drop_column('users', 'share_phone_publicly')
    op.drop_column('users', 'locale')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'tg_id')
    op.drop_index(op.f('ix_favorites_client_user_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_profiles_is_published'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_city_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
